### ISSUE TITLE
script error with pickups and resource warning

### ISSUE THREAD

**Issue by xrtw** [ESX-Org/es_extended#396] opened 2019-11-26 18:58 UTC
```
RegisterNetEvent('esx:removePickup')
AddEventHandler('esx:removePickup', function(id)
	ESX.Game.DeleteObject(pickups[id].obj)
	pickups[id] = nil
end)
```
error is here with nil value
`ESX.Game.DeleteObject(pickups[id].obj)`

**Comment by sutibci** [comment] 2019-12-04 18:28
same..

**Comment by Janicki92** [comment] 2019-12-22 20:32
Same.  It's quite terrible.

**Comment by ElPumpo** [comment] 2020-01-01 18:04
Duplicate of #338

**Closed by ElPumpo** 2020-01-01 18:04 UTC
