### ISSUE TITLE
Flying Mony Bags duplications on server!

### ISSUE THREAD

**Issue by Tinky140** [ESX-Org/es_extended#361] opened 2019-10-12 11:25 UTC
![Untitled3](https://user-images.githubusercontent.com/52570334/66700689-ba668600-ecf3-11e9-839c-69a85b8e5ab0.png)

**Comment by TheRSG** [comment] 2019-10-12 18:23
Can confirm

**Comment by ElPumpo** [comment] 2019-10-13 06:56
Dupe of #338

**Closed by ElPumpo** 2019-10-13 06:56 UTC
