### ISSUE TITLE
Error while setting a job

### ISSUE THREAD

**Issue by CraftYourWay** [ESX-Org/es_extended#16] opened 2017-09-27 01:27 UTC
Error running call reference function for resource es_extended: server/commands.lua:15: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/commands.lua:15: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
Error running call reference function for resource essentialmode: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:378: in upvalue 'callback'
        server/main.lua:213: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>

**Comment by RomainLanz** [comment] 2017-10-10 06:44
You have probably provide a wrong ID to the command.
Closing since not a bug on this resource.

**Closed by RomainLanz** 2017-10-10 06:44 UTC

**Comment by konrad50024** [comment] 2017-10-11 16:10
i have the same issue for some reason and the id is correct it thought it was esx_identity as it uses its primary key as the steam id but it wasnt the issue

**Comment by jakepavek** [comment] 2017-11-10 04:29
same

**Comment by EzequielDM** [comment] 2018-01-28 02:20
Same issue here, will create a new issue
