### ISSUE TITLE
ESX Bug [Seeking Info]

### ISSUE THREAD

**Issue by x0Z3ro0x** [ESX-Org/es_extended#221] opened 2019-03-09 01:25 UTC
Good day, I have an unmodified fresh install of an FXServer and database. However your current ESX build seems to have a bug, but each time a user reports it, the issue just gets closed without any info, advice, comments, or labels being added.

The most recent being here:

[Issue #210](https://github.com/ESX-Org/es_extended/issues/210)
[Issue #157](https://github.com/ESX-Org/es_extended/issues/157)

Perhaps they didn't provide enough info, ect, I'm not sure. However I have a very similar if not exact error, and wish to gain some knowledge vs being swept under the rug.

--------------

Currently as of 3/8/2019 I have the latest files needed to run JUST essentialmode, and ESX. No ESX addons, no custom scripts, no NOTHING extra. To be more specific here is a breakdown of the EXACT version of each and where they were downloaded from:

[Essentialsmode @ version 6.0.2](https://github.com/kanersps/essentialmode/releases/latest)

[mysql-async @ version 3.0.8](https://github.com/brouznouf/fivem-mysql-async)

[esplugin_mysql @ commit e2ff44e](https://github.com/kanersps/esplugin_mysql)

[async @ commit 13cc219](https://github.com/ESX-Org/async)

[ESX @ commit cd9383a](https://github.com/ESX-Org/es_extended)

I have added the following code to the __resource.lua server scripts section of essentialmode:

```
'@mysql-async/lib/MySQL.lua',
'@async/async.lua'
```

and have also added the followed convars to the server.cfg file:

```
set mysql_connection_string "server=localhost;uid=root;password=blahblahblah;database=essentialmode;sslmode=none"
set es_enableCustomData 1
```

--------------

When starting the server everything is clean. No errors, and everything starts up. Here is a picture of our console for further detail:

[Part 1](https://i.ibb.co/hHvk9jQ/consoleprintoff1.png)

[Part 2](https://i.ibb.co/1Qsrsk0/consoleprintoff2.png)

[Part 3](https://i.ibb.co/DDzw8pW/consoleprintoff3.png)

However the moment I or any user attempts connecting, this error is produced:

[Console Error](https://i.ibb.co/tzR6Scj/consoleerror1.png)

This can be reproduced every single time a user connects to the server. Here are my server specs:

[Server Specs](https://i.ibb.co/HnhH34d/serverspecs.png)

Finally our start order follows your instructions and is as follows:

1. mapmanager
2. chat
3. spawnmanager
4. sessionmanager
5. fivem
6. hardcap
7. rconlog
8. scoreboard
9. playernames
10. mysql-async
11. essentialmode
12. esplugin_mysql
13. async
14. es_extended
15. esx_menu_default
16. esx_menu_list
17. esx_menu_dialog

--------------
Any help on this issue when you are not busy would be greatly appreciated. If I have left out any critical info or you just need addition details, please just ask, I will be more than happy to provide anything you need in detail.

**Comment by benzon** [comment] 2019-03-12 04:44
Check your jobs.

The error comes from the job section server side.

You might have changed the default name unemployed to something else, you can only change label of the base job.

```
CREATE TABLE `job_grades` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`job_name` varchar(50) DEFAULT NULL,
	`grade` int(11) NOT NULL,
	`name` varchar(50) NOT NULL,
	`label` varchar(50) NOT NULL,
	`salary` int(11) NOT NULL,
	`skin_male` longtext NOT NULL,
	`skin_female` longtext NOT NULL,

	PRIMARY KEY (`id`)
);

INSERT INTO `job_grades` VALUES (1,'unemployed',0,'unemployed','Unemployed',200,'{}','{}');

CREATE TABLE `jobs` (
	`name` varchar(50) NOT NULL,
	`label` varchar(50) DEFAULT NULL,

	PRIMARY KEY (`name`)
);

INSERT INTO `jobs` VALUES ('unemployed','Unemployed');
```

**Comment by x0Z3ro0x** [comment] 2019-03-12 06:49
> I have an unmodified fresh install of an FXServer and database. 

No jobs were changed at all. Everything was installed fresh and unmodified.

**Comment by boomiiee** [comment] 2019-03-13 10:01
anything? I'm getting the same error and i haven't changed anything either.

**Comment by JustJollyJonah** [comment] 2019-03-13 15:02
Same, we started noticing this issue with just ESX and essentialmode as well.

**Comment by x0Z3ro0x** [comment] 2019-03-13 17:31
Yeah it's definatley a bug and not something we did wrong. Other devs like to suggest it's user error and most of the time they are right. This time they aren't.

The only solution I have found is downgrading essential mode AND esx. I pulled some old server files and used those on a fresh build and it works without error. The issue with this is, outdated code leads to other errors in the new resources.

Those are easier to fix than this bug however so we have went that route. Hopefully we here back from the Dev even if they just admit they dnt have a clue what's causing this. Atleast then we'd get recognition something is being done.

**Comment by boomiiee** [comment] 2019-03-14 02:44
i fixed mine. it was the miner job. for me atleast i kept getting an error because my job was was miner set to grade 4 idk why but yeah check on that

**Comment by x0Z3ro0x** [comment] 2019-03-14 17:44
We have no jobs, this error occurs from a FRESH INSTALL. Downgrading and using the same dB removes the error.

**Comment by shortybsd** [comment] 2019-03-14 22:38
same, it is clearly an esx issue. Try debugging Example `local _source = source
  print("source= ".. tostring(source))
  print("_source= ".. tostring(_source))
	local xPlayer = ESX.GetPlayerFromId(_source)`
line with xPlayer crashes with nil even though the id's are clearly printed on the console/debug window.

**Comment by IllInuz** [comment] 2019-03-23 13:33
Same issue here, while using ESX, Essentialmode, es_extended and a mysql Setup.

**Comment by ElPumpo** [comment] 2019-03-28 07:29
How about spamming "same" just add an emoji. Reason for closing the 'issues' are because they are infact a broken jobs list. I rewrote the part of esx to handle exeptions better for now. Now stop crying and dont expect people to help if you cant find out your own mistakes

**Comment by x0Z3ro0x** [comment] 2019-04-04 19:57
LOL typical smart-ass and complete garbage reply from you. Always on the user to fix YOUR release. An UNMODIFIED, UNALTERED build straight from YOU. Never willing to teach, never willing to help. Always just a "Figure it out yourself or fk off". Just like the very first ticket I ever submitted on this very Github, only to reply later on with a fix for everyone you couldn't be bothered to post.

We did figure it out good sir, just like before, and again with no help from you or your God like ego. You'll never change, but thankfully karma will take care of that. Have a fantastic day and best of wishes to you.

**Comment by ben-sharp** [comment] 2019-04-05 05:05
I had the same issue today with completely fresh install, on player connect. The error occurred because I wasn't setting `mysql_connection_string` early enough in `server.cfg` as is in https://esx-org.github.io/faq/

**Comment by ElPumpo** [comment] 2019-04-05 05:07
Didnt you read my reply?

The problem you are having is caused by an inproper database configuration with the jobs. Latest esx versions added exception handlers for this, checking if every job is valid.
If the job isnt valid it warns in the console, same with invalid job grades.

Now you talk about stuff like "you will nevet change" bitch you broke it learn how to debug what really happened. Its fucking obvious from your error logs that it was an job setup yet you cant fucking read

**Closed by ElPumpo** 2019-04-05 05:07 UTC

**Comment by x0Z3ro0x** [comment] 2019-04-06 18:07
LOL. Case in point right there. Get called on your BS, and all you know how to do is get angry. You're a childish person who can't handle people trying to learn or people questioning you in any manner. Even from an educational stand point. You keep telling me I can't read, and how much of a bitch I am, then turn around and talk shit about how I broke it. 

Perhaps I missed the English language changing it's definition of the word unmodified. Kinda hard to break something that has nothing changed. Not. One. Single. Thing. So if its broke. YOU broke it lmfao.

You talk again about not reading errors and how it's job related, then you reference your own coding on line 134 which is a blank line, and lays inside an INVENTORY function.

```
    table.insert(tasks, function(cb)

      MySQL.Async.fetchAll(
        'SELECT * FROM `user_inventory` WHERE `identifier` = @identifier',
        {
          ['@identifier'] = player.getIdentifier()
        },
        function(inventory)

          local tasks2 = {}

          for i=1, #inventory, 1 do
            table.insert(userData.inventory, {
              name      = inventory[i].item,
              count     = inventory[i].count,
              label     = ESX.Items[inventory[i].item].label,
              limit     = ESX.Items[inventory[i].item].limit,
              usable    = ESX.UsableItemsCallbacks[inventory[i].item] ~= nil,
              rare      = ESX.Items[inventory[i].item].rare,
              canRemove = ESX.Items[inventory[i].item].canRemove,
            })
          end

          for k,v in pairs(ESX.Items) do

            local found = false

            for j=1, #userData.inventory, 1 do
              if userData.inventory[j].name == k then
                found = true
                break
              end
            end

            if not found then

              table.insert(userData.inventory, {
                name      = k,
                count     = 0,
                label     = ESX.Items[k].label,
                limit     = ESX.Items[k].limit,
                usable    = ESX.UsableItemsCallbacks[k] ~= nil,
                rare      = ESX.Items[k].rare,
                canRemove = ESX.Items[k].canRemove,
              })

              local scope = function(item, identifier)

                table.insert(tasks2, function(cb2)

                  MySQL.Async.execute(
                    'INSERT INTO user_inventory (identifier, item, count) VALUES (@identifier, @item, @count)',
                    {
                      ['@identifier'] = identifier,
                      ['@item']       = item,
                      ['@count']      = 0
                    },
                    function(rowsChanged)
                      cb2()
                    end
                  )

                end)

              end

              scope(k, player.getIdentifier())

            end

          end

          Async.parallelLimit(tasks2, 5, function(results) end)

          table.sort(userData.inventory, function(a,b)
            return a.label < b.label
          end)

          cb()
        end
      )

    end)
```

Yes you're right, the error that doesn't reference, name, or label in an capacity any of the jobs, MUST be obvious. I mean as we can clearly see it referencing lines 403, 134, 389, 388, they all come back to job related functions. Yes you are SOOOO right its VERY obvious all we have to do is read:

```
RegisterServerEvent('esx:removeInventoryItem')
AddEventHandler('esx:removeInventoryItem', function(type, itemName, itemCount)

  local _source = source

  if type == 'item_standard' then

    if itemCount == nil or itemCount <= 0 then
      TriggerClientEvent('esx:showNotification', _source, _U('imp_invalid_quantity'))
    else

      local xPlayer   = ESX.GetPlayerFromId(source)
      local foundItem = nil

      for i=1, #xPlayer.inventory, 1 do
        if xPlayer.inventory[i].name == itemName then
          foundItem = xPlayer.inventory[i]
        end
      end
```

So tell us all knowing God. Since it's so obvious that these are job related errors, please bless us with your knowledge on where the coding is failing. Or should I show you those STILL unmodified, unchanged, default jobs just to convince the all powerful that they are in fact correct? Or is all you are capable of is smart ass comments, insults, and dead end advice?

https://i.ibb.co/V21NRfN/jobs.png

**Comment by schwim0341** [comment] 2019-04-06 18:11
If you know the responses to your posts aren't going to be of any assistance to you so why do you continue posting?  Give all of us that are subscribed to the GH issues a break from all the issue updates and discuss with people that will help you, like in the ESX Users helping Users Discord: https://discord.gg/F5e8aEk

**Comment by x0Z3ro0x** [comment] 2019-04-06 18:32
> I had the same issue today with completely fresh install, on player connect. The error occurred because I wasn't setting `mysql_connection_string` early enough in `server.cfg` as is in https://esx-org.github.io/faq/

Thank you for the advice, I double checked our server config, and it's on the third line under the endpoint settings in the config as advised :)

> If you know the responses to your posts aren't going to be of any assistance to you so why do you continue posting? Give all of us that are subscribed to the GH issues a break from all the issue updates and discuss with people that will help you, like in the ESX Users helping Users Discord: https://discord.gg/F5e8aEk

It was started a month ago in hopes that after all this time he'd become a bit more sociable since he is the active Dev, and it's been nearly 6 months since my issue. I continue to post now so that other users can see whats up and hopefully see being a Dev doesn't make you a God, and asking questions is how we learn despite being belittled by a jackass.

Thank you for the discord invite, It's good seeing users help each other esp after the first Discord closed it's doors.

**Comment by benzon** [comment] 2019-04-07 06:29
What the....

> You talk again about not reading errors and how it's job related, then you reference your own coding on line 134 which is a blank line, and lays inside an INVENTORY function.

That is actually very very wrong, the inventory part in main.lua is from 49 to line 120.....

Line 134 IS inside the job section https://github.com/ESX-Org/es_extended/blob/51b2df94aff1ac31e31256d7a2a81a4e75a51cd2/server/main.lua#L122

**Comment by x0Z3ro0x** [comment] 2019-04-07 07:04
> What the....
> 
> > You talk again about not reading errors and how it's job related, then you reference your own coding on line 134 which is a blank line, and lays inside an INVENTORY function.
> 
> That is actually very very wrong, the inventory part in main.lua is from 49 to line 120.....
> 
> Line 134 IS inside the job section
> 
> [es_extended/server/main.lua](https://github.com/ESX-Org/es_extended/blob/51b2df94aff1ac31e31256d7a2a81a4e75a51cd2/server/main.lua#L122)
> 
> Line 122 in [51b2df9](/ESX-Org/es_extended/commit/51b2df94aff1ac31e31256d7a2a81a4e75a51cd2)
> 
>  -- Get job and loadout 
> Besides that screenshot https://i.ibb.co/V21NRfN/jobs.png only shows job grades, not jobs. please try and do SELECT * FROM essentialmode.jobs;

Sorry but that is true. The above code in my last reply is a direct copy and paste from line 134 which is BLANK. So I copied the function that the blank line lays in, which is a get inventory function. The other mentioned lines in the error are the second part I posted which again is inventory coding.

Here is that screenshot you asked for as well as the line number to show I did copy that coding from the lines in the error and they do in fact match up to what I pasted here :)

https://i.ibb.co/Fq12Tgf/jobs.png

https://i.ibb.co/PxHGRrc/server-lua.png

**Comment by x0Z3ro0x** [comment] 2019-04-07 07:27
Users having similar issues:

https://github.com/ESX-Org/es_extended/issues/244
