### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by KillerVillager** [ESX-Org/es_extended#230] opened 2019-03-24 19:17 UTC
Please help me

Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: @es_extended/server/main.lua:163: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/main.lua:163: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)

**Comment by BackrndSource** [comment] 2019-03-24 20:08
When it happens? when you try to connect with client?

**Comment by Luzox** [comment] 2019-03-25 12:25
Yep have the same problem

**Comment by KillerVillager** [comment] 2019-03-25 14:19
> When it happens? when you try to connect with client?

Yes

**Comment by BackrndSource** [comment] 2019-03-26 15:56
I think it's the same isue:
#221 
But there's not solved, downgrade es_extenden is the solution by the moment

**Comment by ElPumpo** [comment] 2019-03-28 07:26
Dupe of #221

**Closed by ElPumpo** 2019-03-28 07:26 UTC
