### ISSUE TITLE
Inventory saves an item with count 0, increase of query time due to inefficiency

### ISSUE THREAD

**Issue by yannickboy15** [ESX-Org/es_extended#323] opened 2019-08-05 02:07 UTC
I guess the title explains it pretty much.

Here's an image:

<img width="586" alt="Schermafbeelding 2019-08-05 om 04 04 19" src="https://user-images.githubusercontent.com/20385056/62433803-49748200-b736-11e9-899b-5844de75bcb4.png">

Why would data be stored when it's 0? I'd say you remove them and add them when they retrieve an item again. In the current situation you're creating a huge query which shouldn't be necessary. I don't mind making a PR for this, I just need to know where this is all being handled.

**Comment by BetterSister** [comment] 2019-08-05 10:57
I was lazy so i just made script that deletes all with count 0 instead of fixing original problem

**Comment by yannickboy15** [comment] 2019-08-05 18:34
Could do that, but that's making a workaround instead of fixing the issue hehe.

**Comment by kohaine** [comment] 2019-08-07 14:39
DELETE FROM `user_inventory` where count = 0

**Comment by BetterSister** [comment] 2019-08-07 17:00
Still doesn't fix the cause of this issue

**Comment by schwim0341** [comment] 2019-08-07 19:21
Yes but since not a single person is offering a fix for the issue, this is a fantastic band aid for those that would like to improve the performance of any query having to work in inventory.

**Comment by SW1FT** [comment] 2019-08-10 11:08
This issue is in server/main.lua (line 83), for whoever was wondering:

![imagem](https://user-images.githubusercontent.com/6627739/62821111-52ff4f00-bb67-11e9-834f-5d3b453ef781.png)

**Comment by BetterSister** [comment] 2019-08-10 11:16
Part of the issue yes but why does it have to insert dummy lines in db? It could just return count 0 of item that wasn't found instead of having thousands of 0 entries

**Comment by BetterSister** [comment] 2019-08-10 11:19
It will break things for sure because inventory checks db if player has any of these items then uses the count to do things. It could just return nil and inventory checks if nil then count = 0

**Comment by yannickboy15** [comment] 2019-08-10 11:22
I'll see if I can change this code to fix this.

**Comment by BetterSister** [comment] 2019-08-10 16:22
https://github.com/ESX-Org/es_extended/blob/5159e892fe1ecc5758600dbbaa342299206720db/server/functions.lua#L60

**Comment by H0ssein** [comment] 2019-09-23 18:35
also there is a glitch with esx_mafia jobs that can make items go under 0 . how can i stop that ?

**Comment by ElPumpo** [comment] 2020-01-01 14:36
Duplicate of #177

**Closed by ElPumpo** 2020-01-01 14:36 UTC
