### ISSUE TITLE
esx:onPlayerDeath trigger broken

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/es_extended#106] opened 2018-07-11 22:41 UTC
When someone is dead he can open inventory when he is kille by someone :(

**Comment by djowdobom** [comment] 2018-07-13 21:53
i'm having the same problem, can u check my issue to see if it matches to yours?

**Comment by ElPumpo** [comment] 2018-07-14 19:13
Duplicate of #108

**Closed by ElPumpo** 2018-07-14 19:13 UTC
