### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by Frelas** [ESX-Org/es_extended#804] opened 2020-05-28 11:08 UTC
I'm trying to run pure ESX 2.0.1 on my Ubuntu 18.04 VPS. The final 1.0 version works fine, but the 2.0 version is stuck on loading screen with few errors shown on F8 Console in fivem

https://del.dog/fusesamana.txt

The DB was succesfully initialized and it created some tables.
Also the server console isn't giving any errors or anomalies.

**Comment by indilo53** [comment] 2020-05-28 11:18
Duplicate of #797

**Closed by indilo53** 2020-05-28 11:18 UTC
